# Generated by Django 4.0.2 on 2022-02-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carte',
            name='code',
            field=models.IntegerField(default=1234, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carte',
            name='solde',
            field=models.FloatField(default=0),
        ),
    ]
