# Generated by Django 4.0.2 on 2022-02-12 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0003_transfer_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carte',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='from_carte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='carte.carte'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='to_carte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivers', to='carte.carte'),
        ),
    ]
