# Generated by Django 4.0.2 on 2022-02-14 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0005_remove_transaction_user_transaction_carte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='carte',
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_carte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='carte.carte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_carte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receivers', to='carte.carte'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('retrait', 'Retrait'), ('versement', 'Versement'), ('transfer', 'Transfer')], max_length=22),
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
