# Generated by Django 4.0.2 on 2022-02-15 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0006_remove_transaction_carte_transaction_from_carte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='carte.carte')),
                ('favorite_carte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_carts', to='carte.carte')),
            ],
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('demand_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands_receiver', to='carte.carte')),
                ('demand_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands_sender', to='carte.carte')),
            ],
        ),
    ]
