# Generated by Django 4.0.2 on 2022-02-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0007_favorite_demand'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('accepted', 'Accepted')], default='active', max_length=255),
        ),
    ]
